require:
  - rubocop-rails
  - rubocop-graphql

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

GraphQL/ObjectDescription:
  Enabled: true
  Exclude:
    - '**/*_schema.rb'
    - '**/base/*.rb'
    - '**/root_types/*.rb'
    - '**/graphql/query_context.rb'
