inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rails
  - rubocop-graphql
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'

  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 2

GraphQL/ObjectDescription:
  Enabled: true
  Exclude:
    - '**/*_schema.rb'
    - '**/base/*.rb'
    - '**/root_types/*.rb'
    - '**/graphql/query_context.rb'
